#!/bin/sh

case "$1" in 
  
  start)
    echo "Starting custom modules"
    modprobe hello
    ./usr/bin/scull_load
    ./usr/bin/module_load faulty
    ./usr/bin/aesdchar_load
    #start-stop-daemon --start --name scull_load --exec /usr/bin/scull_load
    #start-stop-daemon --start --name module_load --exec /usr/bin/module_load -- faulty
    #start-stop-daemon --start --name aesdchar_load --exec /usr/bin/aesdchar_load
    ;;

  stop)
    echo "Stopping custom modules"
    rmmod hello
    ./usr/bin/scull_unload
    ./usr/bin/module_unload faulty
    ./usr/bin/aesdchar_unload
    #start-stop-daemon --start --name scull_unload --exec /usr/bin/scull_unload
    #start-stop-daemon --start --name module_unload --exec /usr/bin/module_unload -- faulty
    #start-stop-daemon --start --name aesdchar_unload --exec /usr/bin/aesdchar_unload
    ;;

  *)
    echo "Usage: run ${0} <start | stop> to load or unload the kernel module"
    exit 1
esac

exit 0
