#! /bin/sh

case "$1" in 
  
  start)
    echo "Starting scull and modules"
    modprobe hello
    /usr/bin/module_load faulty 
    /usr/bin/scull_load 
    ;;

  stop)
    echo "Stopping scull and modules"
    rmmod hello
    /usr/bin/module_unload faulty
    /usr/bin/scull_unload
    ;;

  *)
    echo "Usage: run ${0} <start | stop> to load or unload the kernel modules"
    exit 1
esac

exit 0
